### ISSUE TITLE
It runs very slowly under MySql DB.

### ISSUE THREAD

**Issue by xiashao1980** [app-generator/django-datta-able#7]
I just want to change the database from SQLite to MySql. But it is very very very slowly. 
Do you know how to fix this?

**Comment by app-generator** [comment]
Hello @xiashao1980, 

Thank you for using our product. 
The starter uses Django native ORM to access the database and is nothing specific to Mysql, PostgreSQL or any other DBMS.

Pretty sure the problem is `environmental`.  
We will flag this issue on the [common codebase](https://github.com/app-generator/boilerplate-code-django-dashboard) to be scheduled for a benchmark test against MySql. 

https://github.com/app-generator/boilerplate-code-django-dashboard/issues/10

**Comment by xiashao1980** [comment]
It is because of the MySQL version. It is very slow when I connect to V5.7. If I upgrade MySQL to 8.0, then it works properly.
Thanks.

**Comment by app-generator** [comment]
Noted.
Ty for your work.
